### ISSUE TITLE
Unable to parse file diffs for a PR containing a submodule update

### ISSUE THREAD

**Issue by QuietMisdreavus** [softprops/hubcaps#115] opened 2018-04-05 14:22 UTC
The following sample:

```rust
extern crate hubcaps;
extern crate tokio_core;

use tokio_core::reactor::Core;
use hubcaps::{Credentials, Github};

static TOKEN: &'static str = include_str!("github_token");

fn main() {
    let mut core = Core::new().unwrap();
    let client = Github::new(
        "hubcaps-test",
        Some(Credentials::Token(TOKEN.trim().to_string())),
        &core.handle());

    let resp = core.run(client.repo("rust-lang", "rust")
                              .pulls()
                              .get(49536)
                              .files()).unwrap();

    for diff in resp {
        println!("{:#?}", diff);
    }
}
```

...hits the unwrap in the middle, because submodule updates appear in the files listing, but are missing some information:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Codec(ErrorImpl { code: Message("invalid type: null, expected a string"), line: 1, column: 152 }), State { next_error: None, backtrace: None })', libcore/result.rs:945:5
```

I'm not sure how to get the plain JSON for the response, but hopefully the information in the snippet is enough to get to it.

This was with hubcaps 0.4.5 from crates.io.

**Comment by softprops** [comment] 2018-05-14 00:24
@QuietMisdreavus sorry for the long turn around on this. I wasn't able to reproduce the issue with that pr maybe because the actually pr has since changed. I'm going to leave this open but let me know if you run into this again.  For prosperity I've added an [example](https://github.com/softprops/hubcaps/blob/master/examples/pull_files.rs) I can quickly run to test for a new pr.

**Comment by softprops** [comment] 2018-06-29 01:21
Closing this for now. Feel free to reopen

**Closed by softprops** 2018-06-29 01:21 UTC

**Comment by QuietMisdreavus** [comment] 2018-08-23 15:05
Just got back to my sample that ran into this, and hit another submodule-update PR that triggered this: https://github.com/rust-lang/rust/pull/51061. (I don't have the power to re-open the issue here, sorry!)
